CREATE DATABASE IF NOT EXISTS `managerdb`;
CREATE DATABASE IF NOT EXISTS `customerdb`;
CREATE DATABASE IF NOT EXISTS `carddb`;
CREATE DATABASE IF NOT EXISTS `authenticationdb`;
CREATE DATABASE IF NOT EXISTS `catalogdb`;
CREATE DATABASE IF NOT EXISTS `redeemdb`;
