server:
  port: 8081
spring:
  main:
    banner-mode: "off"
  config:
    #Retrieve config data from the config server
    import: optional:configserver:http://config-server:8888/
  profiles:
    active: dev
  application:
    name: manager-service
  cloud:
    config:
      #URI of the config server
      uri: http://config-server
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
    #spring:
      #jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url:  jdbc:mysql://mysqldb/managerdb
    #jdbc:mysql://mysqldb/managerdb
    username: root
    password: root
    platform: mysql
    initialization-mode: always

#Eureka client configurations
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka-server:8761/eureka/
    register_with_eureka: true
    fetch_registry: true
  instance:
    preferIpAddress: true