server:
  port: 8084
spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: statistic-service
#Eureka client configurations
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka-server:8761/eureka/
    register_with_eureka: true
    fetch_registry: true
  instance:
    preferIpAddress: true